blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DPYTHON_EXECUTABLE=/usr/bin/python3
- -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m
- -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
devel_layout: linked
devel_space: devel
extend_path: null
install: true
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
